### ISSUE TITLE
What is the api key of hf-llm-api

### ISSUE THREAD

**Issue by Niansuh** [Hansimov/hf-llm-api#1]
What is the api key of hf-llm-api

**Comment by Hansimov** [comment]
The key can be any string, which means no auth is needed, so the rate limit is low.
And if you would like to use API key, you can create a HuggingFace Token, see below: 
- https://huggingface.co/docs/hub/security-tokens
- https://huggingface.co/settings/tokens

**Comment by Niansuh** [comment]
Thanks

**Comment by Hansimov** [comment]
@Niansuh Feature implemented. See https://github.com/Hansimov/hf-llm-api/issues/4.

**Comment by Niansuh** [comment]
I provide a free API key for GPT-3.5-turbo with unlimited quota. Thanks for making the HF LLM API.

Base_URL: `https://niansuh-oneapi.hf.space/v1`
API Key: `sk-cKvWkVXJM2rDOCbD5eF2474cEb814605Bb2e36B726Ef755d`
