### ISSUE TITLE
sorry sir please unblock me @Niansuh

### ISSUE THREAD

**Issue by ghost** [Hansimov/hf-llm-api#9]
sorry sir please unblock me @Niansuh

I include original author https://github.com/Hansimov

**Comment by Hansimov** [comment]
@rkihacker Then why you remove the commit history of mine and upload the original codes (which is an even worse behavior), and even place your name there? And why you also copy the issues?

I have already reported to GitHub. Good luck.

![image](https://github.com/Hansimov/hf-llm-api/assets/15179365/981a8ce4-71a6-412e-93e4-4289eed444d4)
![image](https://github.com/Hansimov/hf-llm-api/assets/15179365/f9f2cd0f-40f6-4945-8e82-62142216bfe9)
![image](https://github.com/Hansimov/hf-llm-api/assets/15179365/748f5c8c-0487-467f-867f-d58fdab870c5)
